#!/usr/bin/env python3
"""
Utility script to generate SQL DDL from SQLAlchemy ORM models.

This script can be used to:
1. Generate initial bootstrap SQL files from ORM models
2. Verify that ORM models match existing SQL schemas
3. Generate migration SQL by comparing versions

Usage:
    python generate_ddl.py [--output <file>] [--dialect <dialect>]
"""

import argparse

# Add parent directories to path for imports
import sys
from pathlib import Path

from sqlalchemy import create_engine
from sqlalchemy.schema import CreateIndex, CreateTable

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from data.model.python.orm_models import Base


def generate_ddl(dialect="sqlite", output_file=None):
    """
    Generate DDL statements from ORM models.

    Args:
        dialect: SQL dialect to use (sqlite, postgresql, mysql, etc.)
        output_file: Optional file path to write SQL to
    """
    # Create a mock engine for the specified dialect
    if dialect == "sqlite":
        engine = create_engine("sqlite:///:memory:", future=True)
    elif dialect == "postgresql":
        engine = create_engine("postgresql:///:memory:", future=True)
    elif dialect == "mysql":
        engine = create_engine("mysql:///:memory:", future=True)
    else:
        raise ValueError(f"Unsupported dialect: {dialect}")

    sql_statements = []

    # Generate CREATE TABLE statements for each model
    for table in Base.metadata.sorted_tables:
        create_table_sql = str(CreateTable(table).compile(engine))
        sql_statements.append(create_table_sql)

    # Generate CREATE INDEX statements
    for table in Base.metadata.sorted_tables:
        for index in table.indexes:
            create_index_sql = str(CreateIndex(index).compile(engine))
            sql_statements.append(create_index_sql)

    # Combine all statements
    full_sql = ";\n\n".join(sql_statements) + ";\n"

    # Add header comment
    header = f"""-- Generated DDL from ORM models
-- Dialect: {dialect}
-- DO NOT EDIT THIS FILE MANUALLY
-- This file is generated from data/model/python/orm_models.py

"""

    full_sql = header + full_sql

    # Output
    if output_file:
        output_path = Path(output_file)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(full_sql, encoding="utf-8")
        print(f"DDL written to: {output_file}")
    else:
        print(full_sql)

    return full_sql


def generate_bootstrap_sql(output_dir=None):
    """
    Generate a complete bootstrap SQL file that matches the v1 schema structure.
    This includes the initial schema_version record.
    """
    if output_dir is None:
        output_dir = Path(__file__).parent / "v1"
    else:
        output_dir = Path(output_dir)

    output_dir.mkdir(parents=True, exist_ok=True)
    output_file = output_dir / "bootstrap_schema_autogen.sql"

    # Generate base DDL
    ddl = generate_ddl(dialect="sqlite", output_file=None)

    # Add initial schema version insert
    init_version = """
-- Initialize schema version
INSERT INTO schema_version (version, date, label, comment)
VALUES (1, CURRENT_TIMESTAMP, 'stable', 'Initial schema generated from ORM');
"""

    full_sql = ddl + init_version

    output_file.write_text(full_sql, encoding="utf-8")
    print(f"Bootstrap SQL written to: {output_file}")

    return full_sql


def compare_with_existing(version=1):
    """
    Compare generated DDL with existing SQL files to detect differences.
    """
    existing_file = (
        Path(__file__).parent / f"v{version}" / "bootstrap_schema_autogen.sql"
    )

    if not existing_file.exists():
        print(f"No existing file found at {existing_file}")
        return

    existing_sql = existing_file.read_text(encoding="utf-8")
    generated_sql = generate_ddl(dialect="sqlite", output_file=None)

    # Simple comparison (could be enhanced with proper SQL parsing)
    if existing_sql.strip() == generated_sql.strip():
        print("✓ Generated DDL matches existing SQL file")
    else:
        print("✗ Generated DDL differs from existing SQL file")
        print("\n=== EXISTING SQL ===")
        print(existing_sql)
        print("\n=== GENERATED SQL ===")
        print(generated_sql)


def main():
    parser = argparse.ArgumentParser(
        description="Generate SQL DDL from SQLAlchemy ORM models"
    )
    parser.add_argument("--output", "-o", help="Output file path for generated SQL")
    parser.add_argument(
        "--dialect",
        "-d",
        default="sqlite",
        choices=["sqlite", "postgresql", "mysql"],
        help="SQL dialect to use (default: sqlite)",
    )
    parser.add_argument(
        "--bootstrap",
        "-b",
        action="store_true",
        help="Generate complete bootstrap SQL with initial data",
    )
    parser.add_argument(
        "--compare",
        "-c",
        action="store_true",
        help="Compare generated SQL with existing v1 schema",
    )

    args = parser.parse_args()

    if args.bootstrap:
        generate_bootstrap_sql()
    elif args.compare:
        compare_with_existing()
    else:
        generate_ddl(dialect=args.dialect, output_file=args.output)


if __name__ == "__main__":
    main()
