version: "3.8"
name: compose-test

services:
  homereef:
    build:
      context: ../app
      dockerfile: ../containerfile/reef-transflux-test
    container_name: homereef-api
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app:Z
      - ${MEDIA_DIR:-../test-data/media}:/media:Z
      - ../app:/storage/homereef-transflux:Z
    environment:
      - PYTHONPATH=/app/src
    command: python src/app.py serve --reload
