apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homereef-transflux-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage-fast
  resources:
    requests:
      storage: 5Gi
