apiVersion: apps/v1
kind: Deployment
metadata:
  name: homereef-transflux
  labels:
    app: homereef-transflux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homereef-transflux
  template:
    metadata:
      labels:
        app: homereef-transflux
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: homereef-transflux
          image: zot.lan/homereef-transflux:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: homereef-transflux
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
            limits:
              cpu: "6"
              memory: 6Gi
          volumeMounts:
            - name: media
              mountPath: /media
            - name: cache
              mountPath: /cache
            - name: config
              mountPath: /storage/homereef-transflux
          readinessProbe:
            httpGet:
              path: /status
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /status
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 5
      volumes:
        - name: media
          nfs:
            server: nas.lan
            path: /slow/media
        - name: cache
          emptyDir: {}
        - name: config
          persistentVolumeClaim:
            claimName: homereef-transflux-config
