apiVersion: v1
kind: Service
metadata:
  name: homereef-transflux
  labels:
    app: homereef-transflux
spec:
  type: ClusterIP
  selector:
    app: homereef-transflux
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
