version: "3.8"
name: homereef-local

services:
  homereef-transflux:
    build:
      context: ../transflux/app
      dockerfile: ../containerfile/homereef-transflux
    container_name: homereef-transflux
    ports:
      - "8000:8000"
    volumes:
      - ../transflux/app:/storage/homereef-transflux:Z
      - ${MEDIA_DIR:-/home/andrei/Videos}:/media:Z
    environment:
      - PYTHONPATH=/app/src
    restart: unless-stopped

  seaglass:
    build:
      context: ../seaglass
      dockerfile: ../seaglass/containerfiles/Containerfile
    container_name: seaglass
    ports:
      - "5000:5000"
    environment:
      - TRANSFLUX_URL=http://homereef-transflux:8000
    depends_on:
      - homereef-transflux
    restart: unless-stopped
